// @vitest-environment jsdom
import {beforeEach,afterEach,describe,it,expect,vi} from 'vitest';
import {readFileSync} from 'node:fs';
const model=JSON.parse(readFileSync('../data/normalized/model.json','utf-8'));
vi.mock('maplibre-gl',()=>({default:{Map:class{once(name:string,cb:()=>void){if(name==='load')queueMicrotask(cb)}addControl(){}addSource(){}addLayer(){}on(){}setLayoutProperty(){}resize(){}fitBounds(){}getSource(){return{setData(){}}}},AttributionControl:class{},LngLatBounds:class{extend(){}}}}));
let requests:{url:string;data?:any}[]=[];
const tick=async()=>{for(let i=0;i<12;i++)await Promise.resolve()};
beforeEach(async()=>{vi.useFakeTimers();vi.resetModules();requests=[];document.body.innerHTML='<div id="app"></div>';Object.defineProperty(HTMLDialogElement.prototype,'showModal',{configurable:true,value:function(){this.open=true}});Object.defineProperty(HTMLDialogElement.prototype,'close',{configurable:true,value:function(){this.open=false}});vi.stubGlobal('fetch',vi.fn(async(url:string,options?:RequestInit)=>{const data=options?.body?JSON.parse(String(options.body)):undefined;requests.push({url:String(url),data});let result:any={};if(String(url).includes('/bootstrap'))result=model;else if(String(url).includes('/departures'))result={state:'UNAVAILABLE',predictions:[],error:'Test fixture: feed offline'};else if(String(url).includes('/bus/services'))result={services:[{provider:'KMB',route:'103',direction:'I',service_type:'1',stop_id:'fixture-stop',name_tc:'測試站',dest_tc:'測試終點'}]};else if(String(url).includes('/journeys/plan'))result={id:'test-journey',revision:1,status:'CONDITIONAL',legs:[],total_minutes:12,arrival_at:'2026-10-09T15:00:00+08:00',data_state:data.mode,warnings:['TEST ONLY']};else if(String(url).includes('/sources/status'))result={sources:[],static_sources:[{id:'CSDI',status:'TEST'}]};return{ok:true,json:async()=>({result})}}));await import('../src/main');await tick()});
afterEach(()=>{vi.clearAllTimers();vi.useRealTimers();vi.unstubAllGlobals()});
describe('Hong Kong user flows',()=>{
 it('loads actual model nodes and labels schematic geometry',()=>{expect(document.querySelectorAll('#from option').length).toBe(model.nodes.length);expect(document.querySelector('#map-caption')?.textContent).toContain('並非實測');expect(document.querySelector('#eta-state')?.textContent).toBe('UNAVAILABLE')});
 it('swaps exact node ids',()=>{const a=document.querySelector<HTMLSelectElement>('#from')!,b=document.querySelector<HTMLSelectElement>('#to')!;const x=a.value,y=b.value;document.querySelector<HTMLButtonElement>('#swap')!.click();expect(a.value).toBe(y);expect(b.value).toBe(x)});
 it('submits timezone explicit routing preference',async()=>{document.querySelector<HTMLSelectElement>('#preference')!.value='accessible';document.querySelector('#planner')!.dispatchEvent(new Event('submit',{cancelable:true}));await tick();const r=requests.find(r=>r.url.includes('/journeys/plan'))!;expect(r.data.preference).toBe('accessible');expect(r.data.departure_at).toMatch(/\+08:00$/);expect(document.querySelector('#itinerary')?.textContent).toContain('TEST ONLY');expect(document.querySelector<HTMLButtonElement>('#plan-button')!.disabled).toBe(false)});
 it('replay passes virtual clock and mode to data providers',async()=>{const select=document.querySelector<HTMLSelectElement>('#mode')!;select.value='REPLAY';select.dispatchEvent(new Event('change'));document.querySelector('#planner')!.dispatchEvent(new Event('submit',{cancelable:true}));await tick();expect(requests.find(r=>r.url.includes('/journeys/plan'))!.data.virtual_clock).toMatch(/\+08:00$/);expect(requests.some(r=>r.url.includes('mode=REPLAY'))).toBe(true)});
 it('dialog closes and returns unchanged form',async()=>{const original=document.querySelector<HTMLSelectElement>('#from')!.value;document.querySelector<HTMLButtonElement>('#sources-open')!.click();await tick();expect(document.querySelector<HTMLDialogElement>('#source-dialog')!.open).toBe(true);document.querySelector<HTMLButtonElement>('#sources-close')!.click();expect(document.querySelector<HTMLDialogElement>('#source-dialog')!.open).toBe(false);expect(document.querySelector<HTMLSelectElement>('#from')!.value).toBe(original)});
 it('floor and venue switching keeps station context explicit',()=>{document.querySelector<HTMLButtonElement>('[data-venue="AUS"]')!.click();expect(document.querySelector('#venue-title')?.textContent).toContain('柯士甸');expect(document.querySelectorAll('#floors button').length).toBeGreaterThan(1)});
});
