import './style.css';
import {diagramLayout} from './diagram';
import type maplibregl from 'maplibre-gl';
import 'maplibre-gl/dist/maplibre-gl.css';
type N={id:string;venue_id:string;name_tc:string;name_en?:string;level_id:string;kind:string;x:number;y:number;lon?:number;lat?:number};
type E={id:string;from_id:string;to_id:string;kind:string;minutes:number;evidence:unknown;facility_id?:string};
type Venue={id:string;name_tc:string;name_en:string;levels:string[]};
type Boot={venues:Venue[];nodes:N[];edges:E[];version:string;sources:unknown[];geometry_status?:string};
type Leg={from_id:string;to_id:string;kind:string;minutes:number;label:string;evidence:unknown};
type Journey={request?:{from_id:string;to_id:string;departure_at:string;preference?:string};status:string;legs:Leg[];total_minutes:number;walking_minutes:number;warnings:unknown[];arrival_at:string;hsr?:Record<string,unknown>;id:string;revision:string;data_state:string};
const $=<T extends HTMLElement>(s:string)=>document.querySelector<T>(s)!;
const safe=(s:unknown)=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const fmt=(iso:unknown)=>{if(!iso)return '—';const d=new Date(String(iso));return Number.isNaN(d.valueOf())?String(iso):new Intl.DateTimeFormat('zh-HK',{timeZone:'Asia/Hong_Kong',hour:'2-digit',minute:'2-digit',hour12:false}).format(d)};
const desc=(v:unknown)=>typeof v==='string'?v:JSON.stringify(v);
let boot:Boot|undefined,journey:Journey|undefined,venue='ADM',floor='ALL',view='diagram',mode='LIVE',map:maplibregl.Map|undefined,routeController:AbortController|undefined,routeSerial=0;
let selectedNode:string|undefined;
const PREVIEW=import.meta.env.VITE_REPLAY_PREVIEW==='1';
const app=$('#app');app.innerHTML=`
<header><a class="brand" href="#"><span class="brand-icon">港</span><span>香港<span class="brand-en">MAAS / CONNECTED JOURNEYS</span></span></a><nav aria-label="主要區域"><button class="active" id="journey-tab">出行規劃</button><button id="sources-open">資料與來源 ↗</button></nav><div class="clock"><b id="hk-clock">—</b><span>HONG KONG · UTC+8</span></div></header>
<div class="headline"><div><span class="eyebrow">FROM STREET TO PLATFORM</span><h1>每一段，都接得上。</h1><p>巴士站、轉乘月台與高鐵閘口，把旅程連成一條清晰的路。</p></div><div class="headline-meta"><span class="status-dot"></span>研究與工程驗證原型 <b>01 / HONG KONG</b></div></div>
<main><aside class="planner panel"><div class="section-heading"><h2>你的下一程</h2><span>01</span></div><form id="planner"><label for="from">從哪裡出發</label><select id="from" required><option>載入站點…</option></select><div class="route-divider"><span></span><button type="button" id="swap" aria-label="交換起終點">⇅</button><span></span></div><label for="to">目的地</label><select id="to" required><option>載入站點…</option></select><label for="depart">出發時間 <small>香港時間</small></label><input id="depart" type="datetime-local" required><label for="preference">出行偏好</label><select id="preference"><option value="fast">較快到達</option><option value="few_stairs">減少樓梯</option><option value="accessible">嚴格無障礙</option></select><div class="form-line"><label for="mode">資料模式</label><select id="mode"><option value="LIVE">即時 LIVE</option><option value="REPLAY">回放 REPLAY</option><option value="SIMULATED">情景 SIMULATED</option></select></div><details><summary>接續高鐵與設施情景</summary><p class="micro">填寫高鐵時間後，行程目的地改為西九龍實名核驗入口。</p><label for="hsr">高鐵票面出發時間</label><input type="datetime-local" id="hsr"><label for="queue">手續排隊假設 · 分鐘</label><input type="number" id="queue" min="0" max="180" value="10"><label for="closure">情景關閉設施</label><select id="closure"><option value="">不新增情景關閉</option></select><p class="micro">手動關閉僅用於實驗，不代表設施實際停運。</p></details><button type="submit" class="primary" id="plan-button">規劃我的行程 <span>↗</span></button></form><div id="form-status" role="status" aria-live="polite"></div><div class="planner-note"><span>◎</span><p>每條路徑附上來源與證據狀態。未知的無障礙連接不會被當作可通行。</p></div></aside>
<section class="map-panel panel"><div class="map-toolbar"><div><span class="eyebrow">INTERCHANGE AT A GLANCE</span><h2 id="venue-title">金鐘 · Admiralty</h2></div><div class="view-tabs"><button id="diagram-view" class="active">拓撲</button><button id="map-view">地理</button><button id="layers-view">分層</button></div></div><div class="venue-tabs" id="venues"></div><div class="canvas-wrap"><div id="geo-map"></div><svg id="diagram" viewBox="0 0 880 590" role="img" aria-label="车站路径拓扑示意"></svg><div class="map-empty" id="map-empty">正在載入換乘網絡</div><div class="floor-picker" id="floors"></div><div class="map-caption" id="map-caption">路網拓撲示意 · 並非實測比例圖</div><div class="north">N<br>↑</div></div><div class="map-bottom"><div class="legend"><span><i class="leg-route"></i>選定路徑</span><span><i class="leg-link"></i>連接</span><span><i class="leg-unknown"></i>待核驗</span></div><span id="model-version">MODEL —</span></div><div class="source-attribution"><img src="/preview/landsd-logo.svg" alt="地政總署"><span>Map from Lands Department · © Government of the Hong Kong SAR · <a href="https://portal.csdi.gov.hk/csdi-webpage/doc/TNC" target="_blank" rel="noopener">CSDI 使用條款</a></span></div><div id="selected-info" class="selected-info">選擇節點，查看樓層、設施與路徑位置。</div><details class="network-controls"><summary>官方三維路網研究</summary><p class="micro">以官方路段的三維端點計算距離；這些幾何節點尚未全部配準到旅客月台位置。</p><button id="network-load" type="button">載入當前區域路網</button><div class="network-inputs"><label>起點節點<input id="network-from" list="network-nodes" placeholder="先載入路網，可點線段選擇"></label><label>終點節點<input id="network-to" list="network-nodes" placeholder="可輸入節點 ID"></label></div><datalist id="network-nodes"></datalist><button id="network-plan" type="button">計算官方路網路徑</button><p id="network-result" class="micro" role="status"></p></details></section>
<aside class="results"><section class="panel eta-panel"><div class="section-heading"><h2>下一班列車</h2><span class="pill" id="eta-state">載入中</span></div><div class="eta-subtitle">金鐘 · 東鐵綫 <span>列車事件時間</span></div><div id="eta-list"><p class="micro">正在查詢官方資料</p></div><div class="eta-footer"><span id="eta-time">—</span><button id="eta-refresh" aria-label="重新取得到站資訊">↻</button></div></section><section class="panel eta-panel"><div class="section-heading"><h2>巴士接續</h2><span class="pill" id="bus-state">載入中</span></div><label for="bus-service">路線與方向</label><select id="bus-service"><option>查詢已核驗站點…</option></select><div id="bus-list"></div><div class="eta-footer"><span id="bus-time">—</span><button id="bus-refresh" aria-label="更新巴士預報">↻</button></div></section><section class="panel itinerary"><div class="section-heading"><h2>逐段走得清楚</h2><span>02</span></div><div id="itinerary"><div class="empty-itinerary"><span>↗</span><h3>先選擇起終點</h3><p>行程將展示樓層變化、出入閘與換乘步驟。</p></div></div></section></aside></main>
<footer><span>HONG KONG MAAS <b>交通，不只是一張地圖。</b></span><button id="export" disabled>匯出行程 JSON ↓</button><span id="connection">連接服務中</span></footer><dialog id="source-dialog"><div class="section-heading"><h2>資料與證據</h2><button id="sources-close" aria-label="關閉資料視窗">✕</button></div><p>即時、回放與情景資料分開呈現；版本與觀測時間隨結果保留。</p><div id="source-content"></div></dialog>`;
function localNow(){const d=new Date(Date.now()+8*3600000);return d.toISOString().slice(0,16)}
$('#depart').setAttribute('value',localNow());$('#hk-clock').textContent=fmt(new Date().toISOString());setInterval(()=>$('#hk-clock').textContent=fmt(new Date().toISOString()),30000);
async function api<T>(url:string,options?:RequestInit):Promise<T>{if(PREVIEW){if(options?.method&&options.method!=='GET')throw new Error('此為記錄資料審閱版；重新規劃需要啟動 Python 後端。');const u=new URL(url,location.origin);let file='';if(u.pathname.endsWith('/bootstrap'))file='bootstrap';else if(u.pathname.endsWith('/sources/status'))file='sources';else if(u.pathname.endsWith('/bus/services'))file='bus-services';else if(u.pathname.includes('/stops/ADM/departures'))file='mtr-adm-eal';else if(u.pathname.includes('/stops/'))return {state:'REPLAY',predictions:[],error:'靜態審閱版沒有此方向的回放預報'} as T;else if(u.pathname.includes('/venues/')&&u.pathname.endsWith('/geometry'))file='geometry-'+u.pathname.split('/')[4]+'-'+u.searchParams.get('layer');else if(u.pathname.includes('/network/'))file='network-'+u.pathname.split('/')[4]+(u.pathname.endsWith('/geometry')?'-geometry':'');if(!file)throw new Error('靜態審閱版不提供此操作');url='/preview/'+file+'.json'}const r=await fetch(url,options);const body=await r.json();if(!r.ok)throw new Error(typeof body.detail==='string'?body.detail:JSON.stringify(body.detail??body));if(body.error)throw new Error(desc(body.error));return body.result??body}
function nodeName(id:string){return boot?.nodes.find(n=>n.id===id)?.name_tc??id}
function nodesOptions(){if(!boot)return;const options=boot.venues.map(v=>`<optgroup label="${safe(v.name_tc)}">${boot!.nodes.filter(n=>n.venue_id===v.id).map(n=>`<option value="${safe(n.id)}">${safe(n.name_tc)} · ${safe(n.level_id)}</option>`).join('')}</optgroup>`).join('');const outside=boot.nodes.filter(n=>!boot!.venues.some(v=>v.id===n.venue_id));const allOptions=options+(outside.length?'<optgroup label="外部換乘節點">'+outside.map(n=>`<option value="${safe(n.id)}">${safe(n.name_tc)}</option>`).join('')+'</optgroup>':'');$('#from').innerHTML=allOptions;$('#to').innerHTML=allOptions;const local=boot.nodes.filter(n=>n.venue_id==='ADM');if(local.length){($<HTMLSelectElement>('#from')).value=local[0].id;($<HTMLSelectElement>('#to')).value=local.at(-1)!.id}const fs=[...new Set(boot.edges.map(e=>e.facility_id).filter(Boolean))];$('#closure').innerHTML='<option value="">不新增情景關閉</option>'+fs.map(id=>`<option value="${safe(id)}">${safe(id)}</option>`).join('')}
function renderVenues(){if(!boot)return;$('#venues').innerHTML=boot.venues.map(v=>`<button data-venue="${v.id}" class="${venue===v.id?'active':''}">${safe(v.name_tc)}<small>${safe(v.name_en)}</small></button>`).join('');$('#venues').querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{venue=b.dataset.venue!;floor='ALL';renderVenues();renderDiagram();if(view!=='diagram')void renderMap()});const v=boot.venues.find(v=>v.id===venue);$('#venue-title').textContent=v?`${v.name_tc} · ${v.name_en}`:venue;$('#floors').innerHTML=['ALL',...(v?.levels??[])].map(l=>`<button data-floor="${safe(l)}" class="${floor===l?'active':''}">${l==='ALL'?'全層':safe(l)}</button>`).join('');$('#floors').querySelectorAll<HTMLButtonElement>('button').forEach(b=>b.onclick=()=>{floor=b.dataset.floor!;renderVenues();if(view==='diagram')renderDiagram();else void renderMap()})}
function renderDiagram(){
 if(!boot)return;
 const nodes=boot.nodes.filter(n=>n.venue_id===venue&&(floor==='ALL'||n.level_id===floor));
 const ids=new Set(nodes.map(n=>n.id));
 const edges=boot.edges.filter(e=>ids.has(e.from_id)&&ids.has(e.to_id));
 $('#map-empty').hidden=nodes.length>0;
 if(!nodes.length){$('#map-empty').textContent='此樓層暫無可展示節點';$('#diagram').innerHTML='';return}
 const endpoints=[$<HTMLSelectElement>('#from').value,$<HTMLSelectElement>('#to').value];
 const {positions,labels}=diagramLayout(nodes,endpoints,selectedNode);
 const routePairs=new Set(journey?.legs.map(l=>l.from_id+'|'+l.to_id)??[]);
 const line=edges.map(e=>{
  const a=positions.get(e.from_id)!,b=positions.get(e.to_id)!;
  const active=routePairs.has(e.from_id+'|'+e.to_id)||routePairs.has(e.to_id+'|'+e.from_id);
  const unknown=/unknown|unverified|provisional|assumed/i.test(desc(e.evidence));
  return `<path d="M${a[0]},${a[1]} L${b[0]},${b[1]}" class="connection ${active?'selected':''} ${unknown?'unknown':''}"><title>${safe(e.kind)} · ${e.minutes} min · ${safe(desc(e.evidence))}</title></path>`;
 }).join('');
 $('#diagram').innerHTML=`<defs><pattern id="grid" width="28" height="28" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r="1" fill="#cfd8d4"/></pattern></defs><rect width="880" height="590" fill="url(#grid)"/>${line}${nodes.map(n=>{
  const p=positions.get(n.id)!,label=labels.get(n.id),endpoint=endpoints.includes(n.id);
  return `<g class="station-node ${endpoint?'endpoint':''} ${selectedNode===n.id?'focused-node':''}" data-node="${safe(n.id)}" tabindex="0" role="button" aria-label="${safe(n.name_tc)} ${safe(n.level_id)}" transform="translate(${p[0]},${p[1]})"><title>${safe(n.name_tc)} · ${safe(n.level_id)} · ${safe(n.kind)} · ${safe(n.id)}</title><circle r="${endpoint?11:7}"/>${label?`<text x="${label.x}" y="${label.y}" text-anchor="middle">${safe(label.text)}</text><text x="${label.x}" y="${label.y+13}" class="level-label" text-anchor="middle">${safe(n.level_id)} · ${safe(n.kind)}</text>`:''}</g>`;
 }).join('')}`;
 $('#diagram').querySelectorAll<SVGGElement>('[data-node]').forEach(el=>{
  const select=()=>{
   const n=nodes.find(n=>n.id===el.dataset.node)!;selectedNode=n.id;
   $('#selected-info').textContent=`${n.name_tc} · ${n.level_id} · ${n.kind}｜節點 ${n.id}`;
   renderDiagram();
   const current=Array.from($('#diagram').querySelectorAll<SVGGElement>('[data-node]')).find(item=>item.dataset.node===n.id);current?.focus();
  };
  el.onclick=select;el.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();select()}};
 });
}
let softwareGeometry:GeoJSON.FeatureCollection|undefined;
let mapSerial=0; let mapReady:Promise<void>|undefined; const geometryCache=new Map<string,GeoJSON.FeatureCollection>();
async function renderMap(){if(!boot)return;const gl=(await import('maplibre-gl')).default;const serial=++mapSerial;softwareGeometry=undefined;const selectedVenue=venue;const v=boot.venues.find(v=>v.id===venue) as Venue & {lon?:number;lat?:number};
 $('#map-empty').hidden=false;$('#map-empty').textContent='載入官方室內空間資料…';
 try{let geo=geometryCache.get(venue);if(!geo){const [levels,units]=await Promise.all(['levels','units'].map(layer=>api<GeoJSON.FeatureCollection>(`/api/v1/venues/${encodeURIComponent(venue)}/geometry?layer=${layer}`)));geo={type:'FeatureCollection',features:[...levels.features.map(f=>({...f,properties:{...f.properties,_layer:'levels'}})),...units.features.map(f=>({...f,properties:{...f.properties,_layer:'units'}}))]};geometryCache.set(venue,geo)}
 if(serial!==mapSerial||selectedVenue!==venue)return;
 const selected:GeoJSON.FeatureCollection={type:'FeatureCollection',features:geo.features.filter(f=>floor==='ALL'||f.properties?.level_short_name_en===floor).map(f=>({...f,properties:{...f.properties,display_base:Math.max(0,(Number(f.properties?.level_z_value)||0)+45),display_top:Math.max(0,(Number(f.properties?.level_z_value)||0)+45)+.6}}))};
 softwareGeometry=selected;if(!selected.features.length)throw new Error('此樓層沒有已取得的官方幾何。可切換全層或拓撲視圖。');
 if(!map){map=new gl.Map({container:'geo-map',center:[v.lon??114.1652,v.lat??22.2791],zoom:17.3,style:{version:8,sources:{},layers:[{id:'background',type:'background',paint:{'background-color':'#e8eee9'}}]},attributionControl:false});map.addControl(new gl.AttributionControl({customAttribution:'室內幾何：香港地政總署 / CSDI · 拓撲路徑另行標注'}));mapReady=new Promise<void>((resolve,reject)=>{map!.once('load',()=>resolve());map!.once('error',e=>reject(e.error))});await mapReady;map.addSource('geometry',{type:'geojson',data:selected});map.addLayer({id:'floor-fill',type:'fill',source:'geometry',paint:{'fill-color':['case',['==',['get','_layer'],'levels'],'#c8d7cd',['==',['get','unit_category'],'stairs'],'#c8a969',['==',['get','unit_restriction'],'restricted'],'#acb6b1','#85b8a9'],'fill-opacity':.6}});map.addLayer({id:'floor-outline',type:'line',source:'geometry',paint:{'line-color':'#4c7e72','line-width':1}});map.addLayer({id:'floor-3d',type:'fill-extrusion',source:'geometry',paint:{'fill-extrusion-base':['get','display_base'],'fill-extrusion-height':['get','display_top'],'fill-extrusion-color':['case',['==',['get','_layer'],'levels'],'#b4c9bc','#6da997'],'fill-extrusion-opacity':.75}});map.on('click','floor-fill',e=>{const f=e.features?.[0];if(f)$('#selected-info').textContent=[f.properties?.unit_name_zh||f.properties?.level_name_zh,f.properties?.level_short_name_en,f.properties?.unit_category,f.properties?.unit_restriction].filter(Boolean).join(' · ')})}
 else {await mapReady;(map.getSource('geometry') as maplibregl.GeoJSONSource).setData(selected);}
 if(serial!==mapSerial)return;map.setLayoutProperty('floor-fill','visibility',view==='layers'?'none':'visible');map.setLayoutProperty('floor-outline','visibility',view==='layers'?'none':'visible');map.setLayoutProperty('floor-3d','visibility',view==='layers'?'visible':'none');
 const bounds=new gl.LngLatBounds();const visit=(a:any)=>{if(typeof a[0]==='number'){bounds.extend([a[0],a[1]])}else a.forEach(visit)};for(const f of selected.features){if(f.geometry.type!=='GeometryCollection')visit(f.geometry.coordinates)}
 map.resize();map.fitBounds(bounds,{padding:65,pitch:view==='layers'?55:0,bearing:view==='layers'?-25:0,duration:0});$('#map-empty').hidden=true;
 }catch(e){
 if(serial!==mapSerial)return;
 if(softwareGeometry){
  try{
   try{map?.remove()}catch{}map=undefined;mapReady=undefined;
   renderGeographicSVG(softwareGeometry);
   $('#selected-info').textContent=view==='layers'?'此瀏覽器未能啟用 WebGL，已改用官方幾何的二維顯示；樓層仍可切換。':'此瀏覽器未能啟用 WebGL，已改用官方幾何的二維顯示。';
   return;
  }catch{/* Keep any renderer failure bounded; source error payloads are not user-facing copy. */}
 }
 $('#map-empty').hidden=false;
 $('#map-empty').textContent='暫時未能顯示官方幾何，請切換拓撲視圖或稍後再試。';
 $('#selected-info').textContent='地圖顯示不可用；已取得的行程與逐段文字不受影響。';
}
}

function renderGeographicSVG(geo:GeoJSON.FeatureCollection){const all:number[][]=[];const walk=(a:any)=>{if(typeof a[0]==='number')all.push(a);else a.forEach(walk)};for(const f of geo.features)if(f.geometry.type!=='GeometryCollection')walk(f.geometry.coordinates);if(!all.length)return;const minx=Math.min(...all.map(p=>p[0])),maxx=Math.max(...all.map(p=>p[0])),miny=Math.min(...all.map(p=>p[1])),maxy=Math.max(...all.map(p=>p[1]));const cos=Math.cos((miny+maxy)*Math.PI/360),scale=Math.min(740/Math.max(1e-8,(maxx-minx)*cos),440/Math.max(1e-8,maxy-miny));const point=(p:number[])=>[70+(p[0]-minx)*cos*scale,515-(p[1]-miny)*scale];const path=(ring:number[][])=>ring.map((p,i)=>{const a=point(p);return `${i?'L':'M'}${a[0].toFixed(2)},${a[1].toFixed(2)}`}).join(' ')+'Z';$('#geo-map').style.display='none';$('#diagram').style.display='block';$('#diagram').innerHTML='<rect width="880" height="590" fill="#e8eee9"/>'+geo.features.map(f=>{const g=f.geometry;if(g.type!=='Polygon'&&g.type!=='MultiPolygon')return '';const polys=g.type==='Polygon'?[g.coordinates]:g.coordinates;const d=polys.map(poly=>poly.map(path).join(' ')).join(' ');const color=f.properties?._layer==='levels'?'#cfdfd3':f.properties?.unit_restriction==='restricted'?'#a9b8b0':'#80b9a7';return `<path d="${d}" fill="${color}" fill-rule="evenodd" stroke="#527d6c" stroke-width=".6"><title>${safe(f.properties?.unit_name_zh||f.properties?.level_name_zh)} · ${safe(f.properties?.level_short_name_en)}</title></path>`}).join('');$('#map-empty').hidden=true;$('#map-caption').textContent='官方 CSDI 幾何 · 二維軟件渲染 · 請選樓層查看';}

function setView(next:string){view=next;$('#geo-map').style.display=view!=='diagram'?'block':'none';$('#diagram').style.display=view==='diagram'?'block':'none';for(const v of ['diagram','map','layers'])$('#'+v+'-view').classList.toggle('active',v===view);$('#map-caption').textContent=view==='map'?'官方 CSDI 室內幾何 · 路徑拓撲未作實測配準':view==='layers'?'官方樓層高程 · 整體抬升顯示，厚度為示意':'路網拓撲示意 · 並非實測比例圖';if(view!=='diagram')void renderMap();else {mapSerial++;renderDiagram()}}
for(const v of ['diagram','map','layers'])$('#'+v+'-view').onclick=()=>setView(v);
$('#swap').onclick=()=>{const a=$<HTMLSelectElement>('#from'),b=$<HTMLSelectElement>('#to');[a.value,b.value]=[b.value,a.value];renderDiagram()};$('#from').onchange=()=>renderDiagram();$('#to').onchange=()=>renderDiagram();$('#mode').onchange=()=>{mode=$<HTMLSelectElement>('#mode').value;$('#form-status').textContent=mode==='LIVE'?'即時資料將按來源狀態展示。':'已切換至 '+mode+'，不表示現場實況。';void refreshETA();void refreshBus()};
const hsrLabels:Record<string,string>={verification_margin_minutes:'實名核驗餘量（分鐘）',boarding_margin_minutes:'登車閘口餘量（分鐘）',verification_complete_at:'預計核驗完成',boarding_ready_at:'預計可登車',wait_before_process_minutes:'手續開放前等待（分鐘）',departure_at:'票面出發時間',limiting_stage:'限制環節',rule_version:'規則版本',source_url:'規則來源',assumptions:'時間假設',warnings:'注意事項',status:'接續狀態'};
function showJourney(j:Journey){journey=j;const warnings=j.warnings??[];$('#itinerary').innerHTML=`<div class="journey-summary"><div><strong>${Number.isFinite(j.total_minutes)?Math.ceil(j.total_minutes):'—'}</strong><span>分鐘 · ${safe(j.data_state??mode)}</span></div><p>預計 ${safe(fmt(j.arrival_at))} 到達</p></div><span class="result-status">${safe(j.status)}</span>${warnings.map(w=>`<p class="warning">${safe(desc(w))}</p>`).join('')}<ol class="steps">${(j.legs??[]).map((l,i)=>`<li><span class="step-index">${i+1}</span><div><h3>${safe(l.label||l.kind)}</h3><p>${safe(nodeName(l.from_id))} → ${safe(nodeName(l.to_id))}</p><small>${Number(l.minutes).toFixed(1)} 分鐘 · ${safe(desc(l.evidence))}</small></div></li>`).join('')}</ol>${j.hsr?`<div class="hsr-box"><h3>高鐵接續 · 兩道時間關口</h3>${Object.entries(j.hsr).map(([k,v])=>`<p><span>${safe(hsrLabels[k]??k)}</span><b>${safe(desc(v))}</b></p>`).join('')}</div>`:''}<p class="micro">行程 ${safe(j.id??'未建立')} · 修訂 ${safe(j.revision??'—')}</p>`;($<HTMLButtonElement>('#export')).disabled=!j.id;renderDiagram()}
$('#planner').onsubmit=async e=>{e.preventDefault();routeController?.abort();routeController=new AbortController();const serial=++routeSerial;const button=$<HTMLButtonElement>('#plan-button');button.disabled=true;$('#form-status').textContent='正在核對路徑與接續條件…';const hsr=$<HTMLInputElement>('#hsr').value;const data={from_id:$<HTMLSelectElement>('#from').value,to_id:$<HTMLSelectElement>('#to').value,preference:$<HTMLSelectElement>('#preference').value,departure_at:$<HTMLInputElement>('#depart').value+':00+08:00',mode,...(mode==='REPLAY'?{virtual_clock:$<HTMLInputElement>('#depart').value+':00+08:00'}:{}),closed_facilities:[$<HTMLSelectElement>('#closure').value].filter(Boolean),...(hsr?{hsr_departure:hsr+':00+08:00',queue_minutes:Number($<HTMLInputElement>('#queue').value)}:{})};try{const j=await api<Journey>('/api/v1/journeys/plan',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data),signal:routeController.signal});if(serial!==routeSerial)return;showJourney(j);$('#form-status').textContent='路徑已更新。'}catch(err){if((err as Error).name!=='AbortError'){$('#form-status').textContent=(err as Error).message;$('#itinerary').innerHTML='<p class="warning">未產生可用方案。請查看條件與錯誤說明。</p>';journey=undefined;$<HTMLButtonElement>('#export').disabled=true;renderDiagram()}}finally{if(serial===routeSerial)button.disabled=false}};
let etaBusy=false;async function refreshETA(){if(etaBusy)return;etaBusy=true;try{const d=await api<{state:string;predictions:{event_time:string;dest:string;platform:string;event_type:string}[];source_time:string;error?:string}>('/api/v1/stops/ADM/departures?line=EAL&mode='+mode+(mode==='REPLAY'?'&clock='+encodeURIComponent($<HTMLInputElement>('#depart').value+':00+08:00'):''));$('#eta-state').textContent=d.state;$('#eta-list').innerHTML=d.predictions?.length?d.predictions.slice(0,4).map(p=>`<div class="arrival"><span class="rail-icon">EAL</span><div><b>${safe(p.dest)}</b><small>${safe(p.platform)} 號月台 · ${safe(p.event_type)}</small></div><strong>${safe(fmt(p.event_time))}</strong></div>`).join(''):`<p class="micro">${safe(d.error??'來源未提供可用班次')}</p>`;$('#eta-time').textContent='來源時間 '+fmt(d.source_time)}catch(e){$('#eta-state').textContent='UNAVAILABLE';$('#eta-list').innerHTML=`<p class="micro">${safe((e as Error).message)}</p>`}finally{etaBusy=false}}
$('#eta-refresh').onclick=()=>refreshETA();setInterval(()=>{if(!document.hidden&&mode==='LIVE')void refreshETA()},15000);
$('#sources-open').onclick=async()=>{const dialog=$<HTMLDialogElement>('#source-dialog');dialog.showModal();$('#source-content').textContent='讀取來源狀態…';try{const result=await api<{sources:unknown[];static_sources?:unknown[];probe_records?:unknown[]}>('/api/v1/sources/status');$('#source-content').innerHTML=[...result.sources,...(result.static_sources??[]),...(result.probe_records??[])].map(s=>`<pre>${safe(JSON.stringify(s,null,2))}</pre>`).join('')}catch(e){$('#source-content').textContent=(e as Error).message}};$('#sources-close').onclick=()=>$<HTMLDialogElement>('#source-dialog').close();$('#journey-tab').onclick=()=>$<HTMLSelectElement>('#from').focus();$('#export').onclick=()=>{if(!journey)return;const url=URL.createObjectURL(new Blob([JSON.stringify(journey,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='hongkong-journey-'+journey.id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};

type BusService={provider:string;route:string;direction:string;service_type:string;stop_id:string;name_tc:string;dest_tc:string};let busServices:BusService[]=[];let busSerial=0;
async function initBus(){try{const d=await api<{services:BusService[]}>('/api/v1/bus/services');busServices=d.services;$('#bus-service').innerHTML=busServices.map((b,i)=>`<option value="${i}">${safe(b.route)} → ${safe(b.dest_tc)} · ${safe(b.name_tc)}</option>`).join('');if(!busServices.length)throw new Error('暫無已核驗巴士方向');void refreshBus()}catch(e){$('#bus-state').textContent='UNAVAILABLE';$('#bus-list').textContent=(e as Error).message}}
async function refreshBus(){const serial=++busSerial;const b=busServices[Number($<HTMLSelectElement>('#bus-service').value)];if(!b)return;$('#bus-list').innerHTML='<p class="micro">取得官方預報…</p>';try{const q=new URLSearchParams({provider:b.provider,route:b.route,direction:b.direction,service_type:b.service_type,mode});const d=await api<{state:string;predictions:{event_time:string;dest:string;remark?:string}[];source_time?:string;error?:string}>(`/api/v1/stops/${encodeURIComponent(b.stop_id)}/departures?${q}`);if(serial!==busSerial)return;$('#bus-state').textContent=d.state;$('#bus-list').innerHTML=d.predictions?.length?d.predictions.slice(0,3).map(p=>`<div class="arrival"><span class="rail-icon">${safe(b.route)}</span><div><b>${safe(p.dest)}</b><small>${safe(p.remark||'預計到站')}</small></div><strong>${safe(fmt(p.event_time))}</strong></div>`).join(''):`<p class="micro">${safe(d.error??'此資料模式沒有可用預報')}</p>`;$('#bus-time').textContent='來源時間 '+fmt(d.source_time)}catch(e){if(serial!==busSerial)return;$('#bus-state').textContent='UNAVAILABLE';$('#bus-list').innerHTML=`<p class="micro">${safe((e as Error).message)}</p>`}}
$('#bus-service').onchange=()=>void refreshBus();$('#bus-refresh').onclick=()=>void refreshBus();setInterval(()=>{if(!document.hidden&&mode==='LIVE')void refreshBus()},60000);



function renderNetworkSVG(geo:GeoJSON.FeatureCollection){const features=geo.features.filter(f=>f.geometry.type==='LineString');const points=features.flatMap(f=>(f.geometry as GeoJSON.LineString).coordinates);if(!points.length)return;const minx=Math.min(...points.map(p=>p[0])),maxx=Math.max(...points.map(p=>p[0])),miny=Math.min(...points.map(p=>p[1])),maxy=Math.max(...points.map(p=>p[1]));const cos=Math.cos((miny+maxy)*Math.PI/360),scale=Math.min(740/Math.max(1e-8,(maxx-minx)*cos),440/Math.max(1e-8,maxy-miny));$('#geo-map').style.display='none';$('#diagram').style.display='block';$('#diagram').innerHTML='<rect width="880" height="590" fill="#e8eee9"/>'+features.map(f=>`<path tabindex="0" role="button" aria-label="${safe(f.properties?.kind)}路段" data-from="${safe(f.properties?.from_id)}" data-to="${safe(f.properties?.to_id)}" d="${(f.geometry as GeoJSON.LineString).coordinates.map((p,i)=>`${i?'L':'M'}${70+(p[0]-minx)*cos*scale},${515-(p[1]-miny)*scale}`).join(' ')}" fill="none" stroke="${f.properties?.kind==='stairs'?'#b28f58':'#187e7b'}" stroke-width="2.5"><title>${safe(f.properties?.name_tc||f.properties?.kind)} · ${safe(f.properties?.length_m)} m</title></path>`).join('');$('#diagram').querySelectorAll<SVGPathElement>('path').forEach(el=>{const select=()=>{const id=networkPick%2===0?el.dataset.from:el.dataset.to;if(!id)return;$<HTMLInputElement>(networkPick%2===0?'#network-from':'#network-to').value=id;networkPick++;$('#network-result').textContent='已選 '+id};el.onclick=select;el.onkeydown=e=>{if(e.key==='Enter')select()}});$('#map-empty').hidden=true;$('#map-caption').textContent='官方三維路網的平面投影 · 跨層交叉不自動連接';}

let networkRegion='ADM';let networkPick=0;let networkToken=0;
async function loadOfficialNetwork(){const token=++networkToken;networkRegion=venue==='ADM'?'ADM':'HUB';$('#network-result').textContent='讀取官方三維行人路網…';try{const [g,geom]=await Promise.all([api<{nodes:{id:string;z:number;locations:string[];lon:number;lat:number}[]}>(`/api/v1/network/${networkRegion}`),api<GeoJSON.FeatureCollection>(`/api/v1/network/${networkRegion}/geometry`)]);if(token!==networkToken)return;if(venue==='WEK'){venue='AUS';renderVenues()}view='map';$('#geo-map').style.display='block';$('#diagram').style.display='none';await renderMap();$('#network-nodes').innerHTML=g.nodes.map(n=>`<option value="${safe(n.id)}">${safe(n.locations.join('/'))} · z=${n.z.toFixed(1)}m</option>`).join('');if(!map){renderNetworkSVG(geom);$('#network-result').textContent=`已載入 ${g.nodes.length} 個官方節點，使用二維軟件渲染。`;if(PREVIEW)$<HTMLButtonElement>('#network-plan').disabled=true;return}const source=map.getSource('official-network') as maplibregl.GeoJSONSource|undefined;if(source)source.setData(geom);else{map.addSource('official-network',{type:'geojson',data:geom});map.addLayer({id:'official-network-lines',type:'line',source:'official-network',paint:{'line-color':'#147d87','line-width':3,'line-opacity':.8}});map.on('click','official-network-lines',e=>{const p=e.features?.[0]?.properties;if(!p)return;const input=$<HTMLInputElement>(networkPick%2===0?'#network-from':'#network-to');input.value=networkPick%2===0?p.from_id:p.to_id;networkPick++;$('#network-result').textContent=`已選 ${input.value}。下一次點擊設定${networkPick%2===0?'起點':'終點'}。`})}networkPick=0;$('#network-result').textContent=`已載入 ${g.nodes.length} 個三維節點。可點線段或輸入節點 ID。`;if(PREVIEW){$<HTMLButtonElement>('#network-plan').disabled=true;$('#network-result').textContent+=' 靜態預覽可查看路網；重新計算需啟動後端。'}}catch(e){$('#network-result').textContent=(e as Error).message}}
$('#network-load').onclick=()=>void loadOfficialNetwork();$('#network-plan').onclick=async()=>{const button=$<HTMLButtonElement>('#network-plan');button.disabled=true;try{const r=await api<{status:string;total_minutes?:number;distance_m?:number;geometry?:GeoJSON.FeatureCollection;warnings:unknown[]}>(`/api/v1/network/${networkRegion}/route`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({from_node:$<HTMLInputElement>('#network-from').value,to_node:$<HTMLInputElement>('#network-to').value,preference:$<HTMLSelectElement>('#preference').value,closed_facilities:[]})});$('#network-result').textContent=`${r.status} · ${r.distance_m??'—'} m · ${r.total_minutes??'—'} 分鐘。 ${(r.warnings??[]).map(desc).join(' ')}`;if(r.geometry&&!map)renderNetworkSVG(r.geometry);if(r.geometry&&map){const source=map.getSource('network-route') as maplibregl.GeoJSONSource|undefined;if(source)source.setData(r.geometry);else{map.addSource('network-route',{type:'geojson',data:r.geometry});map.addLayer({id:'network-route-line',type:'line',source:'network-route',paint:{'line-color':'#d39131','line-width':7}})}}}catch(e){$('#network-result').textContent=(e as Error).message}finally{button.disabled=false}};

async function init(){try{boot=await api<Boot>('/api/v1/bootstrap');nodesOptions();renderVenues();renderDiagram();$('#model-version').textContent='MODEL '+boot.version;$('#connection').textContent='模型已載入 · '+boot.nodes.length+' 節點';if(PREVIEW){mode='REPLAY';$<HTMLSelectElement>('#mode').value='REPLAY';$<HTMLSelectElement>('#mode').disabled=true;$<HTMLButtonElement>('#plan-button').disabled=true;$('#plan-button').textContent='重新規劃需啟動後端';$('.headline-meta').textContent='REPLAY · 已記錄資料審閱版';$('#form-status').textContent='官方幾何與記錄資料可互動查看；不是正在運行的即時服務。';fetch('/preview/journey-example.json').then(r=>r.ok?r.json():null).then(j=>{if(j){const example:Journey=j.result??j;const request=example.request;if(request){$<HTMLSelectElement>('#from').value=request.from_id;$<HTMLSelectElement>('#to').value=request.to_id;const departure=new Date(request.departure_at);if(!Number.isNaN(departure.valueOf()))$<HTMLInputElement>('#depart').value=new Date(departure.valueOf()+8*3600000).toISOString().slice(0,16);if(request.preference)$<HTMLSelectElement>('#preference').value=request.preference}showJourney(example);$('#form-status').textContent='表單已對齊右側的已計算樣例與記錄出發時間；這是唯讀記錄，修改表單不會重新規劃。'}}).catch(()=>{})}void refreshETA();void initBus()}catch(e){$('#connection').textContent='服務未連接';$('#map-empty').textContent='請啟動香港 MaaS 後端服務';$('#form-status').textContent=(e as Error).message;$<HTMLButtonElement>('#plan-button').disabled=true}}
void init();
